apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: stripe-store
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer 